G21 (This is GCode, generated with Skeinforge version 35 from ReplicatorG)
G21 (Ultimaker profile - Quality print from alterations/start.gcode)
G21 (Metric: The unit is a millimeter)
M18 (Disable motors for now, to allow manual moving of the head)
G90 (Absolute positioning)
G92 X0 Y0 Z0 E0 (set origin to current position)
(T0 M109 S135 set heated-build-platform temperature)
G91 (Relative positioning)
G1 Z35 F400 (lower platform for cleaning nozzle)
G92 E0 (zero the extruded length)
G1 E260 F1000 (extrude some to get the flow going)
G1 E-20 F3000 (reverse a little)
G92 E0 (zero the extruded length)
M1 (Clean the nozzle and press YES to continue...)
G1 Z-1 F100 (rise platform again)
G1 Z-34 F400 (rise platform again)
G90 (Absolute positioning)
G1 Z0.4 (Tool slightly above the platform)
G92 Z0.4 E0 (zero the extruded length)
G21 (end of start.txt)
